### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by cjhong** [raphael-group/copulacci#1]
I have considered a way to compute a gene expression correlation coefficient in a spatial context and it was lucky for me to find this method (copulacci). Our lab reviewed the bioinformatics paper recently published and it was very interesting! I am considering applying the copulaci to 10x Visium HD data. I am also wondering if the method can handle such high-resolution data in a reasonable computational resource and time. I couldn't find any performance evaluation in the manuscript. Thank you!

*** I followed the installation instructions. I created a conda environment w/ python=3.9, git clone, and run setup. I got this error message and the installation failed with the following error message. Is there any installation requirement? I searched Google w/ the error message but I have no clue.
--------
Collecting urllib3[socks]<3,>=1.26 (from selenium->spatialdm->copulacci==0.0.1)
  Using cached urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
  Using cached urllib3-2.2.0-py3-none-any.whl.metadata (6.4 kB)
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
  Using cached urllib3-2.0.7-py3-none-any.whl.metadata (6.6 kB)
  Using cached urllib3-2.0.6-py3-none-any.whl.metadata (6.6 kB)
  Using cached urllib3-2.0.5-py3-none-any.whl.metadata (6.6 kB)
  Using cached urllib3-2.0.4-py3-none-any.whl.metadata (6.6 kB)
  Using cached urllib3-2.0.3-py3-none-any.whl.metadata (6.6 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "xxx/miniforge3/envs/copulacci/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "xxx/miniforge3/envs/copulacci/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "xxx/miniforge3/envs/copulacci/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "xxx/miniforge3/envs/copulacci/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "xxx/miniforge3/envs/copulacci/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "xxx/miniforge3/envs/copulacci/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 457, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 200000
--------

**Comment by hiraksarkar** [comment]
Hi @cjhong ,

Apologies for late reply, somehow I missed messages from github. Thanks for pointing out the installation error. The error seems to stem from a dependency within packages I used to compare. I just tried the following to resolve this issue, 

Installing these packages separately helps
```
pip install selenium spatialdm
pip install squidpy
```
After this you can 
```
pip install .
```
As now updated in the README. 

For Visium HD data, you are absolutely right about the scaling concerns. In general copulacci works alright for high resolution data such as SeqFISH, but the permutation test portion is time consuming. One way to make it fast is to use multiple threads. I can share the scripts if it is of any help. 

Thanks again!
